// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/database.types.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            workspaces: {
                Row: {
                    id: string
                    name: string
                    slug: string
                    created_at: string
                    updated_at: string
                    settings: Json
                    is_active: boolean
                }
                Insert: {
                    id?: string
                    name: string
                    slug: string
                    created_at?: string
                    updated_at?: string
                    settings?: Json
                    is_active?: boolean
                }
                Update: {
                    id?: string
                    name?: string
                    slug?: string
                    created_at?: string
                    updated_at?: string
                    settings?: Json
                    is_active?: boolean
                }
            }
            profiles: {
                Row: {
                    id: string
                    workspace_id: string | null
                    email: string
                    full_name: string | null
                    role: 'admin' | 'staff' | 'client'
                    avatar_url: string | null
                    phone: string | null
                    created_at: string
                    updated_at: string
                    metadata: Json
                }
                Insert: {
                    id: string
                    workspace_id?: string | null
                    email: string
                    full_name?: string | null
                    role?: 'admin' | 'staff' | 'client'
                    avatar_url?: string | null
                    phone?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
                Update: {
                    id?: string
                    workspace_id?: string | null
                    email?: string
                    full_name?: string | null
                    role?: 'admin' | 'staff' | 'client'
                    avatar_url?: string | null
                    phone?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
            }
            clients: {
                Row: {
                    id: string
                    workspace_id: string
                    user_id: string | null
                    name: string
                    email: string
                    phone: string | null
                    company: string | null
                    address: string | null
                    created_at: string
                    updated_at: string
                    metadata: Json
                }
                Insert: {
                    id?: string
                    workspace_id: string
                    user_id?: string | null
                    name: string
                    email: string
                    phone?: string | null
                    company?: string | null
                    address?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
                Update: {
                    id?: string
                    workspace_id?: string
                    user_id?: string | null
                    name?: string
                    email?: string
                    phone?: string | null
                    company?: string | null
                    address?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
            }
            matters: {
                Row: {
                    id: string
                    workspace_id: string
                    client_id: string
                    reference: string
                    title: string
                    description: string | null
                    status: 'active' | 'pending' | 'closed' | 'archived'
                    opened_at: string
                    closed_at: string | null
                    assigned_to: string | null
                    created_by: string | null
                    created_at: string
                    updated_at: string
                    metadata: Json
                }
                Insert: {
                    id?: string
                    workspace_id: string
                    client_id: string
                    reference: string
                    title: string
                    description?: string | null
                    status?: 'active' | 'pending' | 'closed' | 'archived'
                    opened_at?: string
                    closed_at?: string | null
                    assigned_to?: string | null
                    created_by?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
                Update: {
                    id?: string
                    workspace_id?: string
                    client_id?: string
                    reference?: string
                    title?: string
                    description?: string | null
                    status?: 'active' | 'pending' | 'closed' | 'archived'
                    opened_at?: string
                    closed_at?: string | null
                    assigned_to?: string | null
                    created_by?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
            }
            deadlines: {
                Row: {
                    id: string
                    workspace_id: string
                    matter_id: string
                    title: string
                    description: string | null
                    due_date: string
                    priority: string
                    is_completed: boolean
                    completed_at: string | null
                    assigned_to: string | null
                    created_by: string | null
                    created_at: string
                    updated_at: string
                    metadata: Json
                }
                Insert: {
                    id?: string
                    workspace_id: string
                    matter_id: string
                    title: string
                    description?: string | null
                    due_date: string
                    priority?: string
                    is_completed?: boolean
                    completed_at?: string | null
                    assigned_to?: string | null
                    created_by?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
                Update: {
                    id?: string
                    workspace_id?: string
                    matter_id?: string
                    title?: string
                    description?: string | null
                    due_date?: string
                    priority?: string
                    is_completed?: boolean
                    completed_at?: string | null
                    assigned_to?: string | null
                    created_by?: string | null
                    created_at?: string
                    updated_at?: string
                    metadata?: Json
                }
            }
            files: {
                Row: {
                    id: string
                    workspace_id: string
                    matter_id: string
                    name: string
                    category: 'pleadings' | 'evidence' | 'client_communication' | 'research' | 'internal' | 'contracts' | 'correspondence'
                    mime_type: string | null
                    size_bytes: number | null
                    storage_path: string
                    uploaded_by: string | null
                    uploaded_at: string
                    version: number
                    is_client_visible: boolean
                    metadata: Json
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    workspace_id: string
                    matter_id: string
                    name: string
                    category?: 'pleadings' | 'evidence' | 'client_communication' | 'research' | 'internal' | 'contracts' | 'correspondence'
                    mime_type?: string | null
                    size_bytes?: number | null
                    storage_path: string
                    uploaded_by?: string | null
                    uploaded_at?: string
                    version?: number
                    is_client_visible?: boolean
                    metadata?: Json
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    workspace_id?: string
                    matter_id?: string
                    name?: string
                    category?: 'pleadings' | 'evidence' | 'client_communication' | 'research' | 'internal' | 'contracts' | 'correspondence'
                    mime_type?: string | null
                    size_bytes?: number | null
                    storage_path?: string
                    uploaded_by?: string | null
                    uploaded_at?: string
                    version?: number
                    is_client_visible?: boolean
                    metadata?: Json
                    created_at?: string
                    updated_at?: string
                }
            }
            messages: {
                Row: {
                    id: string
                    workspace_id: string
                    matter_id: string
                    sender_id: string | null
                    recipient_id: string | null
                    subject: string | null
                    body: string
                    is_read: boolean
                    read_at: string | null
                    created_at: string
                    metadata: Json
                }
                Insert: {
                    id?: string
                    workspace_id: string
                    matter_id: string
                    sender_id?: string | null
                    recipient_id?: string | null
                    subject?: string | null
                    body: string
                    is_read?: boolean
                    read_at?: string | null
                    created_at?: string
                    metadata?: Json
                }
                Update: {
                    id?: string
                    workspace_id?: string
                    matter_id?: string
                    sender_id?: string | null
                    recipient_id?: string | null
                    subject?: string | null
                    body?: string
                    is_read?: boolean
                    read_at?: string | null
                    created_at?: string
                    metadata?: Json
                }
            }
            activity_log: {
                Row: {
                    id: string
                    workspace_id: string
                    user_id: string | null
                    activity_type: 'matter.create' | 'matter.update' | 'matter.close' | 'client.create' | 'client.update' | 'file.upload' | 'file.download' | 'file.delete' | 'deadline.create' | 'deadline.update' | 'message.send' | 'user.invite'
                    entity_type: string | null
                    entity_id: string | null
                    description: string
                    ip_address: string | null
                    user_agent: string | null
                    metadata: Json
                    created_at: string
                }
                Insert: {
                    id?: string
                    workspace_id: string
                    user_id?: string | null
                    activity_type: 'matter.create' | 'matter.update' | 'matter.close' | 'client.create' | 'client.update' | 'file.upload' | 'file.download' | 'file.delete' | 'deadline.create' | 'deadline.update' | 'message.send' | 'user.invite'
                    entity_type?: string | null
                    entity_id?: string | null
                    description: string
                    ip_address?: string | null
                    user_agent?: string | null
                    metadata?: Json
                    created_at?: string
                }
                Update: {
                    id?: string
                    workspace_id?: string
                    user_id?: string | null
                    activity_type?: 'matter.create' | 'matter.update' | 'matter.close' | 'client.create' | 'client.update' | 'file.upload' | 'file.download' | 'file.delete' | 'deadline.create' | 'deadline.update' | 'message.send' | 'user.invite'
                    entity_type?: string | null
                    entity_id?: string | null
                    description?: string
                    ip_address?: string | null
                    user_agent?: string | null
                    metadata?: Json
                    created_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            user_role: 'admin' | 'staff' | 'client'
            matter_status: 'active' | 'pending' | 'closed' | 'archived'
            file_category: 'pleadings' | 'evidence' | 'client_communication' | 'research' | 'internal' | 'contracts' | 'correspondence'
            activity_type: 'matter.create' | 'matter.update' | 'matter.close' | 'client.create' | 'client.update' | 'file.upload' | 'file.download' | 'file.delete' | 'deadline.create' | 'deadline.update' | 'message.send' | 'user.invite'
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}
